[package]
name = "chess_engine"
version = "0.1.0"
edition = "2024"

## Enable a small amount of optimization in the dev profile.
#[profile.dev]
#opt-level = 1
#
## Enable a large amount of optimization in the dev profile for dependencies.
#[profile.dev.package."*"]
#opt-level = 3


[dependencies]
either = "1.15.0"
pgn-reader = "0.27.0"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
bincode = "2.0.1"
approx = "0.5.1"
criterion = { version = "0.8.1", features = ["html_reports"] }


[[bench]]
name = "filter_legal_moves"
harness = false

#[[bench]]
#name = "get_all_move_for_turn"
#harness = false